-- ============================================================================
-- Multi-Agent AI Deep Researcher — core schema
-- Extensions, tables, indexes, and updated_at trigger.
-- RLS policies, the vector-match function, and storage live in later migrations.
-- ============================================================================

-- pgvector for embedding similarity search (installed in the extensions schema).
create extension if not exists vector with schema extensions;

-- ---------------------------------------------------------------------------
-- updated_at helper
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- research_runs
-- ---------------------------------------------------------------------------
create table if not exists public.research_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  question text not null,
  status text not null default 'queued',
  mode text not null default 'live',
  scope jsonb,
  plan jsonb,
  report_markdown text,
  quality jsonb,
  error_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists research_runs_user_created_idx
  on public.research_runs (user_id, created_at desc);

create trigger research_runs_set_updated_at
  before update on public.research_runs
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- uploaded_files
-- ---------------------------------------------------------------------------
create table if not exists public.uploaded_files (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  storage_path text unique not null,
  original_name text not null,
  mime_type text not null,
  size_bytes bigint not null,
  ingestion_status text not null default 'pending',
  page_count integer,
  error_summary text,
  created_at timestamptz not null default now()
);

create index if not exists uploaded_files_user_created_idx
  on public.uploaded_files (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- document_chunks (pgvector: gte-small -> 384 dimensions)
-- ---------------------------------------------------------------------------
create table if not exists public.document_chunks (
  id uuid primary key default gen_random_uuid(),
  file_id uuid not null references public.uploaded_files (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  chunk_index integer not null,
  page_number integer,
  content text not null,
  token_count integer,
  metadata jsonb,
  embedding extensions.vector(384),
  created_at timestamptz not null default now(),
  unique (file_id, chunk_index)
);

create index if not exists document_chunks_file_idx
  on public.document_chunks (file_id);

-- HNSW cosine index for similarity search. Cheap to maintain at this scale.
create index if not exists document_chunks_embedding_idx
  on public.document_chunks using hnsw (embedding extensions.vector_cosine_ops);

-- ---------------------------------------------------------------------------
-- sources (web + pdf citations for a run)
-- ---------------------------------------------------------------------------
create table if not exists public.sources (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.research_runs (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  source_key text not null,
  source_type text not null,
  title text not null,
  url text,
  excerpt text,
  citation_metadata jsonb,
  created_at timestamptz not null default now(),
  unique (run_id, source_key)
);

create index if not exists sources_run_idx on public.sources (run_id);

-- ---------------------------------------------------------------------------
-- agent_events (streamed progress, persisted for replay)
-- ---------------------------------------------------------------------------
create table if not exists public.agent_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.research_runs (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  sequence integer not null,
  agent_name text not null,
  status text not null,
  message text not null,
  safe_metadata jsonb,
  created_at timestamptz not null default now(),
  unique (run_id, sequence)
);

create index if not exists agent_events_run_sequence_idx
  on public.agent_events (run_id, sequence);
